### ISSUE TITLE
Error when button is pressed on the website

### ISSUE THREAD

**Issue by akshika47** [akshika47/AmbientLights#4]
[2018-04-02 02:26:29,312] ERROR in app: Exception on /button [GET]
Traceback (most recent call last):
  File "/Users/akshika/PycharmProjects/Lights/venv/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/akshika/PycharmProjects/Lights/venv/lib/python3.5/site-packages/flask/app.py", line 1615, in full_dispatch_request
    return self.finalize_request(rv)
  File "/Users/akshika/PycharmProjects/Lights/venv/lib/python3.5/site-packages/flask/app.py", line 1630, in finalize_request
    response = self.make_response(rv)
  File "/Users/akshika/PycharmProjects/Lights/venv/lib/python3.5/site-packages/flask/app.py", line 1725, in make_response
    raise ValueError('View function did not return a response')
ValueError: View function did not return a response
127.0.0.1 - - [02/Apr/2018 02:26:29] "GET /button HTTP/1.1" 500 -

**Comment by akshika47** [comment]
It was fixed with this commit 
https://github.com/akshika47/AmbientLights/commit/cfec77b4c2bc2a9baf1eda3c600c6962ab029728

Return statement was added.
